language: ruby
script: "./_script/run-tests.sh"
# Keep Travis from testing `master` branch
branches:
  except:
  - master
cache: bundler
sudo: false
rvm:
- 2.2.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: ol4s+iUpSC3U0+dhIcefHohs02ehUIpOHTnsd6MNGFIkFK65rP13ytQfhwcLsZtUBx6T+gA+ECRvJc/Ild4rRYPfyjr0Ao/7khQJX6sU9rXxxmoKVgIe+Fz6e9W89atZoLVLjeHmEQSZUkzyOAl6F+25h4Q26sB7aRvoTPcnRGAMG4lDwz/SC5gXS7ENN1f+7avm2bB08TRc5ic/PQu5q01/vlyA6El2/VOWF8z+Q51eAtDeQGlkm2kQ66poK8H8olZzg+bYn/Vrjq9umQ09Ic2R+/zbChRPaoVYcRw7tp0N3EyT4hJU1WGQ6CZbNfv2+c5TMCEBe16Fit0Ad6/g9bqZhKZuGBm7GpB3DXbi8Zuv2faq/2hgQ6TAPF9VNrKpufbS0c2OtlKcjXGlueeLf6aEHuCM9sDQkxs2akW0hM000h0Plw9rjnla0q4bnNv9GjC4fH4c5ICjCBXNMhtUYcR6ij2jop3F/3VztsP6oY3E9PzqKuAR7KgP8nYe4mbk3rwGGFYUiC+2UC/MDm6FCwkXlc3RhGLBKwjDZ6dkCpp2kAb0j6nhKPJhB61i1N45PysAyqYcMI9jL+YU1gMUE27nhZgTakdgNPLagcFcbUXyrPLq7G4TR2GP0ZojwXGYRQXZU8bB8ROBR/oaucT67dtsyyE51ZnSqxTT9RmxCVo=
  - secure: se57AiyuBsM6iDgeds61CtNKpR9aPCbKswt519AzR4morwUvY+1ItvvDi2H9Y6C/JKzBOLGL7wQELkC8b+fv9RR7xZOHMZRnezmns7t/EU8povx5kBKfvTf2Y0uyJFXsrUIVaghQHNm/Oy79+evpsgjbbqOMmHbtUkeWHMs4AiVLfXo9zZCtDWJs7eZVdDNN/gDFE1Q1LRVg4jgtIolMvc9QxzluJxAnPPMnBQQlCVbXIvcX3CV1SIfIxZ5x84Se4scIflZux/Q2EF3/p/k8ISJdROoZxOHbu4fsf0qq0GwoQdj4Pf7kGUiyc33CifPzb8je2jxME3doAC+Fr+Li6ZYnHyUH+3pS+AIzurTFX2Gp5gnWQ4cM11sFq+P4bbunboMmXnmxVXe/XZeJ7/5KJaQ3WPsoCvthUR0fl+YEnOAavxjDlkjV25iYoH8HuM3hpEkOVHXyJouMVkWkF4vQlMoHCVp1jMN/psgeJGefo192V7316L2bc96uBd4XvyOgG77c2TeKLDtQzjwhrjX4Q6bQetL9W92iqR31KASQ4/gIcrgNLawxKL7BxtY0wxINLSbv8zA3AFL3IPkgDgnALnTIXbRkxMvqy7JE/tLqzQ+ENUa1keLDs47MjMrZJxGO4fH80x0SuwB8BTNemHHEH2QKKxTzGuxrBdhrpXmrdVo=
# Deployment config
deploy:
  provider: script
  script: "./_scripts/build.sh"
  skip_cleanup: false
  on:
    branch: source
