name: Kyle Niewiada's Website
author:
  name: Kyle Niewiada
  email: kyle@kyleniewiada.org
description: My little corner of the Internet where I write about projects I've figured out
timezone: 'America/Detroit'
locale: "en-US"

paginate_path: blog/page/:num/
permalink: blog/:year/:month/:title/

#Collection of single pages. Helps keep organized.
collections:
  pages:
    output: true

markdown: kramdown
highlighter: rouge
paginate: 5
url: https://www.kyleniewiada.org
baseurl: "" # does not include hostname

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - node_modules
  - gulpfile.js
  - CNAME
  - config.rb
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# Serving
detach:  false
port:    4000
host:    localhost
