name: Kyle Niewiada
author:
  name: Kyle Niewiada
  email: kyle@kyleniewiada.org
description: My little corner of the Internet


paginate_path: blog/page:num/
permalink: blog/:year/:month/:title/

markdown: kramdown
highlighter: rouge
paginate: 5
url: https://www.kyleniewiada.org
#enforce_ssl: www.kyleniewiada.org
#url: http://localhost:4000
#excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

# Serving
detach:  false
port:    4000
host:    localhost
baseurl: "" # does not include hostname
