name: Kyle Niewiada
description: My little corner of the Internet


paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5
url: https://www.kyleniewiada.org
enforce_ssl: www.kyleniewiada.org
#url: http://localhost:4000

navigation:
 - title: Home
   url: /#index.html
 - title: About
   url: /about.html
 - title: Archive
   url: /archive.html
 - title: Contact
   url: /contact.html
 - title: Music
   url: http://www.music.kyleniewiada.org/

gems:
  - jekyll-sitemap

# Serving
detach:  false
port:    4000
host:    localhost
baseurl: "" # does not include hostname

social:
   github: aav7fl
   twitter: CrypticCitrus
   facebook: Niewiada
   youtube: KyleNiewiada
   #bandcamp: Custom url used

google_analytics: "UA-37567352-1"
