name: Kyle Niewiada's Website
author: Kyle Niewiada
description: My little corner of the Internet where I write about projects I've figured out
timezone: America/Detroit
locale: "en-US"

paginate_path: blog/page/:num/
permalink: blog/:year/:month/:title/

ampdir: /amp

# Collection of single pages. Helps keep organized.
collections:
  pages:
    output: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax-highlighter: rouge

paginate: 5
url: "https://www.kyleniewiada.org"
baseurl: ""

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - node_modules
  - gulpfile.js
  - CNAME
  - config.rb
  - Gemfile
  - Gemfile.lock
  - package.json
  - Rakefile
  - README.md
  - script
  - vendor

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Serving
detach:  false
port:    3000
host:    localhost

#Social/SEO
twitter:
  username: CrypticCitrus
facebook:
  app_id: 137961485759
logo: /assets/logo.jpg
social:
  links:
    - https://www.facebook.com/KyleNiewiada
    - https://twitter.com/CrypticCitrus
    - https://www.youtube.com/KyleNiewiada
    - https://plus.google.com/u/0/+KyleNiewiada
    - https://kyleniewiada.bandcamp.com
    - https://github.com/aav7fl/
    - https://www.linkedin.com/in/kyleniewiada

#Defaults
defaults:
  - scope:
      path: _posts
    values:
      layout: post
      author: Kyle Niewiada
      seo:
        type: BlogPosting
  - scope:
      path: ""
    values:
      image:
        path: /assets/img/default-card.png
        alt: Default-card
        height: 400
        width: 700
