name: Kyle Niewiada
author:
  name: Kyle Niewiada
  email: kyle@kyleniewiada.org
description: My little corner of the Internet


paginate_path: blog/page:num/
permalink: blog/:year/:month/:title/

markdown: kramdown
highlighter: rouge
paginate: 5
url: https://www.kyleniewiada.org
#enforce_ssl: www.kyleniewiada.org
#url: http://localhost:4000
#excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
sass:
  sass_dir: _sass
  style: compressed

navigation:
 - title: Home
   url: /
 - title: About
   url: /about/
 - title: Archive
   url: /archive/
 - title: Contact
   url: /contact/
 - title: Music
   url: http://music.kyleniewiada.org/
 - title: Résumé
   url: /resume/
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Serving
detach:  false
port:    4000
host:    localhost
baseurl: "" # does not include hostname

social:
   github: aav7fl
   twitter: CrypticCitrus
   youtube: KyleNiewiada
   #bandcamp: Custom url used

google_analytics: "UA-37567352-1"
