name: Kyle Niewiada
description: My little corner of the Internet


paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5
#url: http://www.kyleniewiada.org
#url: http://localhost:4000

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Archive
   url: /archive.html
 - title: Contact
   url: /contact.html
 - title: Music
   url: http://www.music.kyleniewiada.org/

# Serving
detach:  false
port:    4000
host:    localhost
baseurl: "" # does not include hostname
