name: Kyle Niewiada
description: My little corner of the Internet

url: http://localhost:4000
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: true
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html
 - title: Music
   url: http://www.music.kyleniewiada.org/
