name: Kyle Niewiada
description: My little corner of the Internet


paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
rogue: true
paginate: 5
url: https://www.kyleniewiada.org
enforce_ssl: www.kyleniewiada.org
#url: http://localhost:4000

navigation:
 - title: Home
   url: /
 - title: About
   url: /about/
 - title: Blog
   url: /blog/
 - title: Contact
   url: /contact/
 - title: Music
   url: http://music.kyleniewiada.org/

gems:
  - jekyll-sitemap
  - jekyll-paginate

# Serving
detach:  false
port:    4000
host:    localhost
baseurl: "" # does not include hostname

social:
   github: aav7fl
   twitter: CrypticCitrus
   facebook: Niewiada
   youtube: KyleNiewiada
   #bandcamp: Custom url used

google_analytics: "UA-37567352-1"
